- name: Start async task
  ansible.builtin.shell: sleep 60
  async: 120
  poll: 0
  register: async_result

- name: Debug async job ID
  ansible.builtin.debug:
    msg: "Job ID is {{ async_result.ansible_job_id }}"

- name: Wait for async task completion
  ansible.builtin.async_status:
    jid: "{{ async_result.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 40
  delay: 3
