- name: Deploy Application
  hosts: all
  gather_facts: no
 
  tasks:
    - name: Show parameters received from Morpheus
      debug:
        msg: "Deploying {{ user_input }} in {{ dg_environment_code }} for instance {{ instance_name }} (ID: {{ instance_id }})"
 
    - name: Run deployment
      shell: |
        echo "Deploying {{ user_input }} to {{ dg_environment_code }}..."
