- name: Test
  hosts: all
  gather_facts: false

  tasks:
    - name: Template Hello.yml
      copy:
        src: Hello.yml
        dest: /etc/rhsm/ca/Hello.yml
        mode: '0644'

    - name: Write random file with ~3252 characters
      copy:
        dest: /tmp/random_3252.txt
        content: "{{ lookup('password', '/dev/null length=3252 chars=ascii_letters,digits') }}"
        mode: '0644'

    - fail:
        msg: test
