---
- name: Setup OS for GDC GKE on baremetal
  hosts: all
  gather_facts: false
  become: true
  vars:
    sysctl:
      - name: fs.inotify.max_user_instances
        value: 8192
      - name: fs.inotify.max_user_watches
        value: 524288

  tasks:

    - name: Check current user
      ansible.builtin.command:
        cmd: whoami
      register: whoami

    - name: Print current user
      ansible.builtin.debug:
        msg: "Current user is: {{ whoami.stdout }}"

    - name: Fix SSH key file permissions
      ansible.builtin.shell:
        cmd: chmod 600 /etc/ssh/*key
      args:
        executable: /bin/bash

    - name: Install required packages via apt
      ansible.builtin.apt:
        name:
          - wget
          - apt-transport-https
          - gnupg2
          - curl
          - jq
          - vim
          - libuser
          - lsb-release
          - ca-certificates
          - scsitools
        update_cache: true

    - name: Set kernel parameters
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
        sysctl_file: /etc/sysctl.d/99-gdc.conf
      loop: "{{ sysctl }}"

    - name: Create drop-in sub-directory for Systemd-timesyncd
      ansible.builtin.file:
        path: /etc/systemd/timesyncd.conf.d/
        mode: '0755'
        state: directory

    - name: Set NTP servers in Systemd-timesyncd
      ansible.builtin.blockinfile:
        path: /etc/systemd/timesyncd.conf.d/ntp.conf
        block: |
          [Time]
          NTP=time1.google.com time2.google.com
        create: true
        mode: '0644'

    - name: Restart Systemd-timesyncd service
      ansible.builtin.systemd:
        name: systemd-timesyncd.service
        state: restarted
        enabled: true
