---
- name: Create a directory under /home/deepti without become
  hosts: all
  tasks:
  - name: Ensure /home/deepti/pratap directory exists
    file:
      path: /home/deepti/pratap
      state: directory
      mode: '0755'
    become: true
