---
- name: Create a Directory Without Privilege Escalation
  hosts: all
  become: false
  tasks:
  - name: Create a directory named pratap
    file:
      path: "~/pratap"
      state: directory
      mode: '0755'
