---
- name: Install Apache Web Server
  hosts: webservers
  become: yes
  tasks: 
    - name: Install the Apache Web Server
      apt: name=apache2 state=latest
    - name: Start the Apache Web Server
      service: name=apache2 state=started enabled=yes
