---
- name: Install Apache
  hosts: all
  gather_facts: false
  connection: local

  vars:
    ansible_python_interpreter: /usr/bin/python3

  # become: true

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install or Upgrade Apache
      ansible.builtin.apt:
        name: apache2
        state: latest

    - name: Start and enable Apache service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
