---
- name: Test user input via Morpheus
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Show what Morpheus actually passed
      debug:
        var: morpheus['customOptions']

    - name: Print message only if user selected Yes
      debug:
        msg: "Hello! You selected Yes."
      when: morpheus['customOptions']['user_input'] == "Yes"
