---
- name: Test user input via Extra Vars
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Print message only if user_input is Yes
      debug:
        msg: "Hello! You selected Yes."
      when: user_input == "Yes"
