---
- name: Test user input via Morpheus
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Show what Morpheus actually passed
      debug:
        var: user_input

    - name: Print message only if user selected Yes
      debug:
        msg: "Hello! You selected Yes."
      when: "'Yes' in user_input|string"
