---
# This playbook prints a simple debug message
- name: Test morpheus variables 
  hosts: all
  gather_facts: yes
  become: yes
  connection: local

  tasks:
  - name: gather facts
    debug:
      msg: |
        Hello, world! 
        {% if 'instance' in morpheus %}
        {{ morpheus.instance | to_nice_json }}
        {% else %}
        No 'instance' key found in morpheus variable.
        {% endif %}
