Your Ansible playbook appears to be mostly correct, but there's a small syntax issue with the `msg` line. Here's the corrected version of your playbook:

```yaml
---
# This playbook prints a simple debug message
- name: Test morpheus variables 
  hosts: all
  gather_facts: yes
  become: yes
  connection: local

  tasks:
  - name: gather facts
    debug:
      msg: |
        {% if 'instance' in morpheus %}
        {{ morpheus.instance | to_json | safe }}
        {% else %}
        {}
        {% endif %}
